/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSeoGoogleMeuNegocioRouteImport } from './routes/services.seo-google-meu-negocio'
import { Route as ServicesGoogleAdsRouteImport } from './routes/services.google-ads'
import { Route as ServicesGestaoDeRedesSociaisRouteImport } from './routes/services.gestao-de-redes-sociais'
import { Route as ServicesCriacaoDeWebsitesRouteImport } from './routes/services.criacao-de-websites'
import { Route as ServicesBrandingELogotiposRouteImport } from './routes/services.branding-e-logotipos'
import { Route as ServicesAgentesIaRouteImport } from './routes/services.agentes-ia'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSeoGoogleMeuNegocioRoute =
  ServicesSeoGoogleMeuNegocioRouteImport.update({
    id: '/seo-google-meu-negocio',
    path: '/seo-google-meu-negocio',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesGoogleAdsRoute = ServicesGoogleAdsRouteImport.update({
  id: '/google-ads',
  path: '/google-ads',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGestaoDeRedesSociaisRoute =
  ServicesGestaoDeRedesSociaisRouteImport.update({
    id: '/gestao-de-redes-sociais',
    path: '/gestao-de-redes-sociais',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCriacaoDeWebsitesRoute =
  ServicesCriacaoDeWebsitesRouteImport.update({
    id: '/criacao-de-websites',
    path: '/criacao-de-websites',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesBrandingELogotiposRoute =
  ServicesBrandingELogotiposRouteImport.update({
    id: '/branding-e-logotipos',
    path: '/branding-e-logotipos',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAgentesIaRoute = ServicesAgentesIaRouteImport.update({
  id: '/agentes-ia',
  path: '/agentes-ia',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/agentes-ia': typeof ServicesAgentesIaRoute
  '/services/branding-e-logotipos': typeof ServicesBrandingELogotiposRoute
  '/services/criacao-de-websites': typeof ServicesCriacaoDeWebsitesRoute
  '/services/gestao-de-redes-sociais': typeof ServicesGestaoDeRedesSociaisRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/seo-google-meu-negocio': typeof ServicesSeoGoogleMeuNegocioRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/agentes-ia': typeof ServicesAgentesIaRoute
  '/services/branding-e-logotipos': typeof ServicesBrandingELogotiposRoute
  '/services/criacao-de-websites': typeof ServicesCriacaoDeWebsitesRoute
  '/services/gestao-de-redes-sociais': typeof ServicesGestaoDeRedesSociaisRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/seo-google-meu-negocio': typeof ServicesSeoGoogleMeuNegocioRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/agentes-ia': typeof ServicesAgentesIaRoute
  '/services/branding-e-logotipos': typeof ServicesBrandingELogotiposRoute
  '/services/criacao-de-websites': typeof ServicesCriacaoDeWebsitesRoute
  '/services/gestao-de-redes-sociais': typeof ServicesGestaoDeRedesSociaisRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/seo-google-meu-negocio': typeof ServicesSeoGoogleMeuNegocioRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/services/$slug'
    | '/services/agentes-ia'
    | '/services/branding-e-logotipos'
    | '/services/criacao-de-websites'
    | '/services/gestao-de-redes-sociais'
    | '/services/google-ads'
    | '/services/seo-google-meu-negocio'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/privacy'
    | '/quote'
    | '/sitemap.xml'
    | '/terms'
    | '/services/$slug'
    | '/services/agentes-ia'
    | '/services/branding-e-logotipos'
    | '/services/criacao-de-websites'
    | '/services/gestao-de-redes-sociais'
    | '/services/google-ads'
    | '/services/seo-google-meu-negocio'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/services/$slug'
    | '/services/agentes-ia'
    | '/services/branding-e-logotipos'
    | '/services/criacao-de-websites'
    | '/services/gestao-de-redes-sociais'
    | '/services/google-ads'
    | '/services/seo-google-meu-negocio'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/seo-google-meu-negocio': {
      id: '/services/seo-google-meu-negocio'
      path: '/seo-google-meu-negocio'
      fullPath: '/services/seo-google-meu-negocio'
      preLoaderRoute: typeof ServicesSeoGoogleMeuNegocioRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/google-ads': {
      id: '/services/google-ads'
      path: '/google-ads'
      fullPath: '/services/google-ads'
      preLoaderRoute: typeof ServicesGoogleAdsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/gestao-de-redes-sociais': {
      id: '/services/gestao-de-redes-sociais'
      path: '/gestao-de-redes-sociais'
      fullPath: '/services/gestao-de-redes-sociais'
      preLoaderRoute: typeof ServicesGestaoDeRedesSociaisRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/criacao-de-websites': {
      id: '/services/criacao-de-websites'
      path: '/criacao-de-websites'
      fullPath: '/services/criacao-de-websites'
      preLoaderRoute: typeof ServicesCriacaoDeWebsitesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/branding-e-logotipos': {
      id: '/services/branding-e-logotipos'
      path: '/branding-e-logotipos'
      fullPath: '/services/branding-e-logotipos'
      preLoaderRoute: typeof ServicesBrandingELogotiposRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/agentes-ia': {
      id: '/services/agentes-ia'
      path: '/agentes-ia'
      fullPath: '/services/agentes-ia'
      preLoaderRoute: typeof ServicesAgentesIaRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesAgentesIaRoute: typeof ServicesAgentesIaRoute
  ServicesBrandingELogotiposRoute: typeof ServicesBrandingELogotiposRoute
  ServicesCriacaoDeWebsitesRoute: typeof ServicesCriacaoDeWebsitesRoute
  ServicesGestaoDeRedesSociaisRoute: typeof ServicesGestaoDeRedesSociaisRoute
  ServicesGoogleAdsRoute: typeof ServicesGoogleAdsRoute
  ServicesSeoGoogleMeuNegocioRoute: typeof ServicesSeoGoogleMeuNegocioRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesAgentesIaRoute: ServicesAgentesIaRoute,
  ServicesBrandingELogotiposRoute: ServicesBrandingELogotiposRoute,
  ServicesCriacaoDeWebsitesRoute: ServicesCriacaoDeWebsitesRoute,
  ServicesGestaoDeRedesSociaisRoute: ServicesGestaoDeRedesSociaisRoute,
  ServicesGoogleAdsRoute: ServicesGoogleAdsRoute,
  ServicesSeoGoogleMeuNegocioRoute: ServicesSeoGoogleMeuNegocioRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
